// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVUjNwRgs8yJvmqsdagm7TfxcBrUqL9WQ',
    appId: '1:401325778109:web:7c8b5a074dea807d8c43d4',
    messagingSenderId: '401325778109',
    projectId: 'fir-tutorial-583ad',
    authDomain: 'fir-tutorial-583ad.firebaseapp.com',
    storageBucket: 'fir-tutorial-583ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJ_axmSeaXt7E-6LvqWvmL6iAc3g6JNM',
    appId: '1:401325778109:android:27ea89abff14318b8c43d4',
    messagingSenderId: '401325778109',
    projectId: 'fir-tutorial-583ad',
    storageBucket: 'fir-tutorial-583ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FU0uxhBdzX_pCudhd_Unl2G1m6gydEI',
    appId: '1:401325778109:ios:1d354ebcd1dac7cd8c43d4',
    messagingSenderId: '401325778109',
    projectId: 'fir-tutorial-583ad',
    storageBucket: 'fir-tutorial-583ad.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
